[default]
marketplace_project = "adeptmind-public"
auto_approve_entitlements = false
event_topic = '@none None'
slack_webhook = '@none None'
audience = 'api.prod.marketplace.adeptmind.net'
dlp_store_base = 'https://api.dlp-store.dev.dlp.adeptmind.net'
dlp_store_api_key = '@none None'

[global] # global will override everything
is_codelab = false
